import { Category, Difficulty, Question } from "./types";

type Bank = Record<Category, Record<Difficulty, Question[]>>;

export const QUESTIONS: Bank = {
  science: {
    easy: [
      { q: "What planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: 1 },
      { q: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], answer: 2 },
      { q: "How many bones are in the adult human body?", options: ["206", "201", "210", "196"], answer: 0 },
      { q: "Water boils at what temperature (°C) at sea level?", options: ["90", "100", "110", "120"], answer: 1 },
      { q: "What is the largest organ of the human body?", options: ["Liver", "Brain", "Skin", "Lungs"], answer: 2 },
      { q: "Which planet is closest to the Sun?", options: ["Earth", "Venus", "Mercury", "Mars"], answer: 2 },
      { q: "What is H2O commonly known as?", options: ["Salt", "Water", "Hydrogen", "Oxygen"], answer: 1 },
      { q: "Which animal is known as the King of the Jungle?", options: ["Tiger", "Lion", "Elephant", "Bear"], answer: 1 },
      { q: "What do bees produce?", options: ["Milk", "Wax & Honey", "Silk", "Wool"], answer: 1 },
      { q: "Sound travels fastest through?", options: ["Air", "Water", "Vacuum", "Steel"], answer: 3 },
      { q: "Which is the closest star to Earth?", options: ["Polaris", "Sirius", "The Sun", "Alpha Centauri"], answer: 2 },
      { q: "What is the chemical symbol for gold?", options: ["Gd", "Go", "Au", "Ag"], answer: 2 },
    ],
    medium: [
      { q: "What is the speed of light in vacuum (approx)?", options: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10¹⁰ m/s", "3×10⁵ m/s"], answer: 0 },
      { q: "Who proposed the theory of general relativity?", options: ["Newton", "Einstein", "Bohr", "Hawking"], answer: 1 },
      { q: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi"], answer: 2 },
      { q: "What is the pH of pure water?", options: ["5", "6", "7", "8"], answer: 2 },
      { q: "Which element has the symbol 'Fe'?", options: ["Fluorine", "Iron", "Lead", "Tin"], answer: 1 },
      { q: "Which gas makes up most of Earth's atmosphere?", options: ["Oxygen", "Nitrogen", "CO₂", "Argon"], answer: 1 },
      { q: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], answer: 2 },
      { q: "Light year measures?", options: ["Time", "Speed", "Distance", "Brightness"], answer: 2 },
      { q: "DNA stands for?", options: ["Deoxyribonucleic Acid", "Dinitric Acid", "Diribonucleic Acid", "Deoxynitric Acid"], answer: 0 },
      { q: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1 },
      { q: "Photosynthesis primarily occurs in the?", options: ["Roots", "Stem", "Leaves", "Flowers"], answer: 2 },
      { q: "Which is the hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Quartz"], answer: 2 },
    ],
    hard: [
      { q: "What particle was discovered at CERN in 2012?", options: ["Neutrino", "Higgs boson", "Quark", "Muon"], answer: 1 },
      { q: "Heisenberg's principle relates to?", options: ["Energy & mass", "Position & momentum", "Time & space", "Charge & spin"], answer: 1 },
      { q: "Which scientist formulated the laws of planetary motion?", options: ["Galileo", "Kepler", "Copernicus", "Brahe"], answer: 1 },
      { q: "The Krebs cycle occurs in which organelle?", options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"], answer: 2 },
      { q: "Avogadro's number is approximately?", options: ["6.022×10²³", "3.14×10²³", "9.81×10²³", "1.6×10¹⁹"], answer: 0 },
      { q: "Which subatomic particle has no charge?", options: ["Proton", "Electron", "Neutron", "Positron"], answer: 2 },
      { q: "The Doppler effect explains?", options: ["Light bending", "Frequency shift", "Mass increase", "Heat loss"], answer: 1 },
      { q: "Who discovered penicillin?", options: ["Pasteur", "Fleming", "Koch", "Lister"], answer: 1 },
      { q: "Black holes were predicted by which theory?", options: ["Quantum", "Relativity", "String", "M-theory"], answer: 1 },
      { q: "The mole is a unit of?", options: ["Mass", "Volume", "Amount of substance", "Length"], answer: 2 },
      { q: "CRISPR is used for?", options: ["Imaging", "Gene editing", "Protein folding", "Cloning"], answer: 1 },
      { q: "The Schrödinger equation describes?", options: ["Gravity", "Wave function", "Entropy", "Refraction"], answer: 1 },
    ],
  },
  tech: {
    easy: [
      { q: "What does 'CPU' stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Power Unit", "Control Processing Unit"], answer: 0 },
      { q: "Which company makes the iPhone?", options: ["Samsung", "Google", "Apple", "Sony"], answer: 2 },
      { q: "HTML is used to?", options: ["Style pages", "Structure pages", "Query data", "Run servers"], answer: 1 },
      { q: "What does 'www' stand for?", options: ["World Wide Web", "World Web Wire", "Wide Web World", "Web World Wide"], answer: 0 },
      { q: "Which is an operating system?", options: ["Chrome", "Linux", "Photoshop", "Excel"], answer: 1 },
      { q: "RAM stands for?", options: ["Read Access Memory", "Random Access Memory", "Run Active Memory", "Rapid Access Module"], answer: 1 },
      { q: "What does 'USB' stand for?", options: ["Universal Serial Bus", "United System Bus", "Unique Source Bus", "Universal System Byte"], answer: 0 },
      { q: "Which company created Android?", options: ["Apple", "Microsoft", "Google", "Samsung"], answer: 2 },
      { q: "JavaScript runs primarily in?", options: ["Database", "Browser", "Printer", "Router"], answer: 1 },
      { q: "What does 'AI' stand for?", options: ["Auto Input", "Artificial Intelligence", "Active Internet", "Applied Index"], answer: 1 },
      { q: "GitHub is used for?", options: ["Gaming", "Code hosting", "Streaming", "Shopping"], answer: 1 },
      { q: "Which is a search engine?", options: ["Firefox", "Bing", "Outlook", "Slack"], answer: 1 },
    ],
    medium: [
      { q: "Who founded Microsoft?", options: ["Steve Jobs", "Bill Gates", "Larry Page", "Elon Musk"], answer: 1 },
      { q: "Which language is React built with?", options: ["Python", "Ruby", "JavaScript", "Java"], answer: 2 },
      { q: "TCP/IP is a?", options: ["Database", "Protocol suite", "Browser", "OS"], answer: 1 },
      { q: "SQL is used to?", options: ["Style HTML", "Query databases", "Compile code", "Render 3D"], answer: 1 },
      { q: "What does 'HTTP' stand for?", options: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Transit Path", "Host Transfer Protocol"], answer: 0 },
      { q: "Which is NOT a JS framework?", options: ["Vue", "Angular", "Django", "Svelte"], answer: 2 },
      { q: "Linux was created by?", options: ["Linus Torvalds", "Dennis Ritchie", "Ken Thompson", "Bjarne Stroustrup"], answer: 0 },
      { q: "Which company owns YouTube?", options: ["Meta", "Google", "Amazon", "Apple"], answer: 1 },
      { q: "Bitcoin was launched in?", options: ["2005", "2009", "2013", "2017"], answer: 1 },
      { q: "Which is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"], answer: 2 },
      { q: "Docker is primarily used for?", options: ["Containers", "Compilers", "Editors", "Email"], answer: 0 },
      { q: "Which protocol is used for secure web?", options: ["FTP", "HTTPS", "SMTP", "SSH"], answer: 1 },
    ],
    hard: [
      { q: "Big-O of binary search?", options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], answer: 1 },
      { q: "Who invented the World Wide Web?", options: ["Vint Cerf", "Tim Berners-Lee", "Alan Turing", "Ada Lovelace"], answer: 1 },
      { q: "Which sorting algorithm is stable?", options: ["Quick sort", "Heap sort", "Merge sort", "Selection sort"], answer: 2 },
      { q: "Kubernetes was originally developed by?", options: ["Microsoft", "Google", "Red Hat", "IBM"], answer: 1 },
      { q: "Which is NOT an OSI layer?", options: ["Session", "Presentation", "Protocol", "Transport"], answer: 2 },
      { q: "JWT stands for?", options: ["JSON Web Token", "Java Web Tool", "Joint Web Transfer", "JSON Wire Type"], answer: 0 },
      { q: "RSA is a?", options: ["Hash function", "Public key crypto", "Compression", "Database"], answer: 1 },
      { q: "Which paradigm is Haskell?", options: ["OOP", "Functional", "Procedural", "Logic"], answer: 1 },
      { q: "GPT models are based on?", options: ["RNN", "Transformer", "CNN", "GAN"], answer: 1 },
      { q: "TLS replaced?", options: ["FTP", "SSL", "DNS", "ARP"], answer: 1 },
      { q: "Race condition occurs in?", options: ["Single threads", "Concurrent code", "Static sites", "JSON files"], answer: 1 },
      { q: "Which is a memory-safe language?", options: ["C", "C++", "Rust", "Assembly"], answer: 2 },
    ],
  },
  gk: {
    easy: [
      { q: "How many continents are there?", options: ["5", "6", "7", "8"], answer: 2 },
      { q: "Capital of France?", options: ["Berlin", "Paris", "Rome", "Madrid"], answer: 1 },
      { q: "Which is the largest ocean?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
      { q: "Currency of Japan?", options: ["Yuan", "Yen", "Won", "Ringgit"], answer: 1 },
      { q: "Eiffel Tower is in?", options: ["London", "Paris", "Rome", "Madrid"], answer: 1 },
      { q: "How many colors in a rainbow?", options: ["5", "6", "7", "8"], answer: 2 },
      { q: "Which country has the most population?", options: ["USA", "India", "China", "Russia"], answer: 1 },
      { q: "Pyramids are in?", options: ["Mexico", "Egypt", "Greece", "Iraq"], answer: 1 },
      { q: "How many days in a leap year?", options: ["365", "366", "364", "367"], answer: 1 },
      { q: "Largest desert in the world?", options: ["Gobi", "Kalahari", "Sahara", "Antarctic"], answer: 3 },
      { q: "Capital of Australia?", options: ["Sydney", "Canberra", "Melbourne", "Perth"], answer: 1 },
      { q: "Which language has the most native speakers?", options: ["English", "Spanish", "Mandarin", "Hindi"], answer: 2 },
    ],
    medium: [
      { q: "Who wrote 'Romeo and Juliet'?", options: ["Dickens", "Shakespeare", "Hemingway", "Austen"], answer: 1 },
      { q: "Mona Lisa was painted by?", options: ["Van Gogh", "Picasso", "Da Vinci", "Monet"], answer: 2 },
      { q: "Mount Everest is in which range?", options: ["Andes", "Alps", "Himalayas", "Rockies"], answer: 2 },
      { q: "Which country invented paper?", options: ["India", "China", "Egypt", "Greece"], answer: 1 },
      { q: "UN headquarters are in?", options: ["Geneva", "New York", "Paris", "Vienna"], answer: 1 },
      { q: "The Great Wall is in?", options: ["Japan", "Korea", "China", "Mongolia"], answer: 2 },
      { q: "Largest country by area?", options: ["China", "USA", "Canada", "Russia"], answer: 3 },
      { q: "Who painted the Sistine Chapel ceiling?", options: ["Raphael", "Michelangelo", "Donatello", "Botticelli"], answer: 1 },
      { q: "Currency of UK?", options: ["Euro", "Pound", "Dollar", "Krona"], answer: 1 },
      { q: "Which river is the longest?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1 },
      { q: "Vatican City is located in?", options: ["France", "Italy", "Spain", "Greece"], answer: 1 },
      { q: "Statue of Liberty was a gift from?", options: ["UK", "France", "Spain", "Germany"], answer: 1 },
    ],
    hard: [
      { q: "Who was the first UN Secretary-General?", options: ["Trygve Lie", "U Thant", "Kofi Annan", "Dag Hammarskjöld"], answer: 0 },
      { q: "Smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Nauru"], answer: 1 },
      { q: "Author of 'War and Peace'?", options: ["Dostoevsky", "Tolstoy", "Chekhov", "Pushkin"], answer: 1 },
      { q: "Which year did WWII end?", options: ["1943", "1944", "1945", "1946"], answer: 2 },
      { q: "Currency of Switzerland?", options: ["Euro", "Franc", "Krone", "Pound"], answer: 1 },
      { q: "Capital of Mongolia?", options: ["Ulaanbaatar", "Astana", "Bishkek", "Tashkent"], answer: 0 },
      { q: "Which strait separates Asia and North America?", options: ["Bering", "Hormuz", "Malacca", "Magellan"], answer: 0 },
      { q: "Magna Carta was signed in?", options: ["1066", "1215", "1492", "1605"], answer: 1 },
      { q: "Who discovered America?", options: ["Magellan", "Columbus", "Cook", "Vespucci"], answer: 1 },
      { q: "Suez Canal connects?", options: ["Atlantic & Pacific", "Med & Red Sea", "Black & Caspian", "Baltic & North"], answer: 1 },
      { q: "Which empire built Machu Picchu?", options: ["Aztec", "Maya", "Inca", "Olmec"], answer: 2 },
      { q: "Berlin Wall fell in?", options: ["1987", "1989", "1991", "1993"], answer: 1 },
    ],
  },
  movies: {
    easy: [
      { q: "Who directed 'Jurassic Park'?", options: ["Lucas", "Spielberg", "Cameron", "Nolan"], answer: 1 },
      { q: "In Titanic, who plays Jack?", options: ["Brad Pitt", "Tom Cruise", "Leonardo DiCaprio", "Matt Damon"], answer: 2 },
      { q: "'May the Force be with you' is from?", options: ["Star Trek", "Star Wars", "Avatar", "Dune"], answer: 1 },
      { q: "Frozen is by which studio?", options: ["Pixar", "Disney", "DreamWorks", "Sony"], answer: 1 },
      { q: "Who plays Iron Man?", options: ["Chris Evans", "RDJ", "Mark Ruffalo", "Chris Hemsworth"], answer: 1 },
      { q: "Harry Potter's pet owl?", options: ["Hedwig", "Errol", "Pigwidgeon", "Crookshanks"], answer: 0 },
      { q: "Shrek is a?", options: ["Dragon", "Ogre", "Wizard", "Knight"], answer: 1 },
      { q: "The Lion King protagonist?", options: ["Simba", "Mufasa", "Scar", "Nala"], answer: 0 },
      { q: "Director of 'Avatar'?", options: ["Spielberg", "Cameron", "Scorsese", "Tarantino"], answer: 1 },
      { q: "Bruce Wayne is?", options: ["Superman", "Batman", "Spider-Man", "Hulk"], answer: 1 },
      { q: "Forrest Gump's favorite food?", options: ["Pizza", "Shrimp", "Burgers", "Steak"], answer: 1 },
      { q: "Which movie features Woody and Buzz?", options: ["Cars", "Up", "Toy Story", "Coco"], answer: 2 },
    ],
    medium: [
      { q: "Who directed 'Inception'?", options: ["Spielberg", "Nolan", "Cameron", "Fincher"], answer: 1 },
      { q: "Best Picture Oscar 2020?", options: ["1917", "Joker", "Parasite", "Roma"], answer: 2 },
      { q: "The Godfather is directed by?", options: ["Coppola", "Scorsese", "Kubrick", "Lucas"], answer: 0 },
      { q: "Pulp Fiction director?", options: ["Tarantino", "Rodriguez", "Lynch", "Coen"], answer: 0 },
      { q: "'I see dead people' is from?", options: ["The Others", "Sixth Sense", "Insidious", "Paranormal"], answer: 1 },
      { q: "Who played the Joker in Dark Knight?", options: ["Joaquin Phoenix", "Jared Leto", "Heath Ledger", "Jack Nicholson"], answer: 2 },
      { q: "Matrix protagonist?", options: ["Neo", "Morpheus", "Trinity", "Smith"], answer: 0 },
      { q: "Which film won Best Picture in 1994?", options: ["Forrest Gump", "Pulp Fiction", "Shawshank", "Lion King"], answer: 0 },
      { q: "Director of Schindler's List?", options: ["Spielberg", "Polanski", "Allen", "Stone"], answer: 0 },
      { q: "Gladiator main actor?", options: ["Brad Pitt", "Russell Crowe", "Mel Gibson", "Tom Hanks"], answer: 1 },
      { q: "First Pixar feature film?", options: ["Toy Story", "A Bug's Life", "Monsters Inc", "Finding Nemo"], answer: 0 },
      { q: "Hogwarts house of Cedric Diggory?", options: ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"], answer: 1 },
    ],
    hard: [
      { q: "Director of 'Citizen Kane'?", options: ["Hitchcock", "Welles", "Ford", "Capra"], answer: 1 },
      { q: "Who composed the Star Wars score?", options: ["Zimmer", "Williams", "Horner", "Goldsmith"], answer: 1 },
      { q: "First film to win Best Picture Oscar?", options: ["Wings", "Sunrise", "Metropolis", "The Jazz Singer"], answer: 0 },
      { q: "Kurosawa's most famous film?", options: ["Ran", "Rashomon", "Seven Samurai", "Yojimbo"], answer: 2 },
      { q: "Director of '2001: A Space Odyssey'?", options: ["Lucas", "Kubrick", "Scott", "Nolan"], answer: 1 },
      { q: "How many Oscars did 'Titanic' win?", options: ["7", "9", "11", "13"], answer: 2 },
      { q: "Bergman's 'Seventh Seal' features a game with?", options: ["Devil", "Death", "God", "King"], answer: 1 },
      { q: "Director of 'La La Land'?", options: ["Chazelle", "Linklater", "Aronofsky", "Anderson"], answer: 0 },
      { q: "Year 'Casablanca' was released?", options: ["1939", "1942", "1945", "1948"], answer: 1 },
      { q: "Studio behind 'Spirited Away'?", options: ["Toei", "Madhouse", "Ghibli", "Bones"], answer: 2 },
      { q: "Coen brothers' first film?", options: ["Fargo", "Blood Simple", "Big Lebowski", "Raising Arizona"], answer: 1 },
      { q: "Who directed 'There Will Be Blood'?", options: ["Anderson", "Aronofsky", "Fincher", "Malick"], answer: 0 },
    ],
  },
  sports: {
    easy: [
      { q: "How many players in a soccer team on field?", options: ["9", "10", "11", "12"], answer: 2 },
      { q: "Olympics happen every?", options: ["2 yrs", "3 yrs", "4 yrs", "5 yrs"], answer: 2 },
      { q: "How many points is a touchdown?", options: ["3", "6", "7", "10"], answer: 1 },
      { q: "Wimbledon is played on?", options: ["Clay", "Hard", "Grass", "Carpet"], answer: 2 },
      { q: "How many holes in golf?", options: ["9", "16", "18", "20"], answer: 2 },
      { q: "Michael Jordan played mainly for?", options: ["Lakers", "Bulls", "Celtics", "Heat"], answer: 1 },
      { q: "Cricket originated in?", options: ["India", "Australia", "England", "South Africa"], answer: 2 },
      { q: "How many rings on the Olympic flag?", options: ["3", "4", "5", "6"], answer: 2 },
      { q: "F1 stands for?", options: ["First One", "Formula One", "Fast One", "Flag One"], answer: 1 },
      { q: "Tour de France is what sport?", options: ["Running", "Cycling", "Sailing", "Skiing"], answer: 1 },
      { q: "NBA stands for?", options: ["National Basketball Assoc.", "New Basketball Assoc.", "North Ball Assoc.", "Nat'l Boxing Assoc."], answer: 0 },
      { q: "Boxing matches are held in a?", options: ["Court", "Ring", "Pitch", "Arena"], answer: 1 },
    ],
    medium: [
      { q: "Who has the most Grand Slam titles (men, 2024)?", options: ["Federer", "Nadal", "Djokovic", "Murray"], answer: 2 },
      { q: "Country that won FIFA WC 2022?", options: ["France", "Argentina", "Brazil", "Germany"], answer: 1 },
      { q: "Usain Bolt is from?", options: ["USA", "Jamaica", "Kenya", "Trinidad"], answer: 1 },
      { q: "How long is a marathon (km)?", options: ["40", "42.195", "45", "50"], answer: 1 },
      { q: "Super Bowl is the final of?", options: ["MLB", "NBA", "NFL", "NHL"], answer: 2 },
      { q: "First country to win the FIFA World Cup?", options: ["Brazil", "Italy", "Uruguay", "Argentina"], answer: 2 },
      { q: "Lionel Messi mainly plays as?", options: ["GK", "Defender", "Midfielder", "Forward"], answer: 3 },
      { q: "How many players in a basketball team on court?", options: ["4", "5", "6", "7"], answer: 1 },
      { q: "Which sport uses a shuttlecock?", options: ["Tennis", "Squash", "Badminton", "Table Tennis"], answer: 2 },
      { q: "Bundesliga is in which country?", options: ["Spain", "Italy", "Germany", "France"], answer: 2 },
      { q: "How many points for a 3-pointer in basketball?", options: ["1", "2", "3", "4"], answer: 2 },
      { q: "Cricket World Cup 2023 winner?", options: ["India", "Australia", "England", "NZ"], answer: 1 },
    ],
    hard: [
      { q: "Who scored the 'Hand of God' goal?", options: ["Pele", "Maradona", "Zidane", "Ronaldo"], answer: 1 },
      { q: "Year of the first modern Olympics?", options: ["1886", "1896", "1900", "1924"], answer: 1 },
      { q: "Most NBA championships won by one player?", options: ["8", "10", "11", "13"], answer: 2 },
      { q: "Who broke the 100m WR with 9.58s?", options: ["Powell", "Bolt", "Gay", "Gatlin"], answer: 1 },
      { q: "F1 driver with most championships?", options: ["Schumacher", "Hamilton (tied)", "Both tied", "Vettel"], answer: 2 },
      { q: "Year Brazil first won the World Cup?", options: ["1950", "1954", "1958", "1962"], answer: 2 },
      { q: "Wimbledon was first held in?", options: ["1877", "1900", "1923", "1936"], answer: 0 },
      { q: "Decathlon consists of how many events?", options: ["8", "9", "10", "12"], answer: 2 },
      { q: "First woman to win a Formula 1 point?", options: ["Lella Lombardi", "Susie Wolff", "Danica Patrick", "Maria Filippis"], answer: 0 },
      { q: "Cricket: 6 sixes in an over by Yuvraj — against?", options: ["Australia", "England", "SA", "NZ"], answer: 1 },
      { q: "Who won the Ballon d'Or 2023?", options: ["Haaland", "Mbappé", "Messi", "Ronaldo"], answer: 2 },
      { q: "NHL's Stanley Cup is named after?", options: ["A team owner", "Lord Stanley", "A coach", "A city"], answer: 1 },
    ],
  },
};

export function getQuestions(category: Category, difficulty: Difficulty): Question[] {
  const pool = QUESTIONS[category][difficulty];
  const shuffled = [...pool].sort(() => Math.random() - 0.5).slice(0, 10);
  // also shuffle option order while preserving answer
  return shuffled.map((q) => {
    const indexed = q.options.map((opt, i) => ({ opt, i }));
    indexed.sort(() => Math.random() - 0.5);
    return {
      q: q.q,
      options: indexed.map((x) => x.opt),
      answer: indexed.findIndex((x) => x.i === q.answer),
    };
  });
}