/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VictoryRouteImport } from './routes/victory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayLevelRouteImport } from './routes/play.$level'

const VictoryRoute = VictoryRouteImport.update({
  id: '/victory',
  path: '/victory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelRoute = PlayLevelRouteImport.update({
  id: '/play/$level',
  path: '/play/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/victory': typeof VictoryRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/victory': typeof VictoryRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/victory': typeof VictoryRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/victory' | '/play/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/victory' | '/play/$level'
  id: '__root__' | '/' | '/victory' | '/play/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VictoryRoute: typeof VictoryRoute
  PlayLevelRoute: typeof PlayLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/victory': {
      id: '/victory'
      path: '/victory'
      fullPath: '/victory'
      preLoaderRoute: typeof VictoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$level': {
      id: '/play/$level'
      path: '/play/$level'
      fullPath: '/play/$level'
      preLoaderRoute: typeof PlayLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VictoryRoute: VictoryRoute,
  PlayLevelRoute: PlayLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
